import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { Document, YAMLMap, parseDocument } from "yaml";
import type { PackageManager, WizardResult } from "./init-types";

export interface MergeConfigOptions {
  ignoreExisting?: boolean;
}

export function mergeConfig(
  root: string,
  wizardResult: WizardResult,
  packageManager: PackageManager,
  options: MergeConfigOptions = {},
): string {
  const configPath = join(root, ".aos", "config.yaml");
  const raw = !options.ignoreExisting && existsSync(configPath) ? readFileSync(configPath, "utf-8") : "";
  const doc = raw ? parseDocument(raw) : new Document({});
  if (doc.errors.length > 0) {
    throw new Error(doc.errors[0]?.message ?? "Invalid config.yaml");
  }

  if (!(doc.contents instanceof YAMLMap)) {
    doc.contents = new YAMLMap();
  }

  const yamlItems = doc.contents.items as Array<{ key?: { value?: unknown; commentBefore?: string } }>;
  const legacyAdapterPair = yamlItems.find((item) => item.key?.value === "adapter");
  const preservedComment = legacyAdapterPair?.key?.commentBefore;

  doc.delete("adapter");
  doc.set("api_version", "aos/config/v2");
  doc.set("package_manager", packageManager);
  doc.set("models", wizardResult.models);
  doc.set("editor", wizardResult.editor);
  doc.set("adapters", {
    enabled: wizardResult.enabledAdapters,
    default: wizardResult.defaultAdapter,
  });
  doc.set("adapter_defaults", wizardResult.adapterDefaults);

  if (preservedComment && doc.contents.items.length > 0) {
    const updatedItems = doc.contents.items as Array<{ key?: { commentBefore?: string } }>;
    const firstKey = updatedItems[0]?.key;
    if (firstKey && !firstKey.commentBefore) {
      firstKey.commentBefore = preservedComment;
    }
  }

  return doc.toString();
}

export function generateMemoryYaml(projectName: string, provider: "expertise" | "mempalace"): string {
  const providerBlock = provider === "mempalace" ? "mempalace" : "expertise";
  return `# AOS Memory Configuration
# Generated by: aos init
api_version: aos/memory/v1

# Memory provider: "mempalace" (recommended) or "expertise" (built-in fallback)
provider: ${providerBlock}

# MemPalace settings (used when provider: mempalace)
# mempalace:
#   palace_path: ~/.mempalace/palace
#   project_wing: ${projectName}
#   wake_layers: [L0, L1]
#   auto_hall: true
#   max_wake_tokens: 1200
#   max_drawer_tokens: 500

# Built-in expertise settings (used when provider: expertise)
expertise:
  max_lines: 200
  scope: per-project

# Orchestrator memory behavior
orchestrator:
  remember_prompt: session_end
  recall_gate: true
  max_recall_per_session: 10
`;
}
