import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

export const PI_EXTENSION_FILE = "aos-harness.ts";

export function getProjectPiExtensionPath(projectRoot: string): string {
  return join(projectRoot, ".pi", "extensions", PI_EXTENSION_FILE);
}

export function getGlobalPiExtensionPath(home = homedir()): string {
  return join(home, ".pi", "agent", "extensions", PI_EXTENSION_FILE);
}

export function hasPiExtensionShim(projectRoot: string): boolean {
  return existsSync(getProjectPiExtensionPath(projectRoot)) || existsSync(getGlobalPiExtensionPath());
}

export function projectPiShimContent(): string {
  return `// Auto-generated by \`aos init\`. Do not edit.
// This file enables /aos-run in Pi when opened in this project.
// Regenerate with: aos init --adapter pi
export { default } from "@aos-harness/pi-adapter";
`;
}

export function globalPiShimContent(): string {
  return `// Auto-generated by \`aos setup-pi --global\`. Do not edit.
// This file enables /aos-run in Pi for all AOS projects.
// Regenerate with: aos setup-pi --global
export { default } from "@aos-harness/pi-adapter";
`;
}

function writeShim(path: string, content: string): string {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
  return path;
}

export function writeProjectPiShim(projectRoot: string): string {
  return writeShim(getProjectPiExtensionPath(projectRoot), projectPiShimContent());
}

export function writeGlobalPiShim(home = homedir()): string {
  return writeShim(getGlobalPiExtensionPath(home), globalPiShimContent());
}

export function ensureProjectPiGitignore(projectRoot: string): string {
  const gitignorePath = join(projectRoot, ".gitignore");
  const entry = ".pi/extensions/";
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf-8") : "";
  const lines = existing.split(/\r?\n/).map((line) => line.trim());
  if (lines.includes(entry)) {
    return gitignorePath;
  }

  const prefix = existing.length === 0 || existing.endsWith("\n") ? existing : `${existing}\n`;
  writeFileSync(gitignorePath, `${prefix}${entry}\n`, "utf-8");
  return gitignorePath;
}
